### PR TITLE
Feature/#13 integrate database

### LINKED ISSUE #13: Integrate User database and User repository
1. Add Dependencies: Add the Spring Boot Data Cassandra starter to`build.gradle` file. This starter includes auto-configuration support for Cassandra and the Cassandra Java driver, as well as Spring Data Cassandra which provides abstractions for storing and querying your data.
2. Configure Cassandra Properties: In `application.properties` file, specify properties like the keyspace name, contact points (IP addresses of the Cassandra nodes), and port. Specify other properties like the consistency level, load balancing policy, etc.
3. Setup Database: Set up the Cassandra database. Use a local installation for development, but for production, likely use a Cassandra cluster.
4. Create Data Models: These are entity classes that map to tables in your Cassandra database. Annotate these classes with `@Table` and the fields with `@Column` or `@PrimaryKey`.
5. Create Repositories: These interfaces extend CassandraRepository or ReactiveCassandraRepository and provide methods for common CRUD operations. Can also define custom methods.
6. Use Repositories in Your Services and Controllers: Use `@Autowire` your repositories into your services to use in business logic, and then your services can be used in controllers to handle HTTP requests.
7. Write Tests for Cassandra DB: Use the CassandraRepository.

### PR DESCRIPTION
**Pull request by Xu-Gavin**
Closes #13.

I added basic support with Cassandra database for the `User` model. Future models will be supported later.

Testcontainers was not implemented. Integration with testcontainers is was not successful and will be addressed in issue #15. Though, I've added the dependencies for the testcontainers already in `build.gradle`.

### CODE REVIEW

**Comment by Xu-Gavin** [comment]
@itsmarsss There is a failing test, let me try to resolve it before reviewing.

**Comment by Xu-Gavin** [comment]
> @itsmarsss There is a failing test, let me try to resolve it before reviewing.

Test seems to fail because theres no Cassandra database docker container running on GitHub's CI environment...

**Comment by Xu-Gavin** [comment]
Test will not fail when docker image is running in the background with default initialization:
```shell
docker run -p 9042:9042 --rm --name cassandra -d cassandra:4.0.7
docker exec -it cassandra bash -c "cqlsh -u cassandra -p cassandra"
CREATE KEYSPACE spring_cassandra WITH replication = {'class' : 'SimpleStrategy', 
'replication_factor' : 1};
```
Screen Shot 2023-12-07 at 11 38 44 AM

Otherwise, it will fail. I will push a commit that attempts to run a cassandra service in the background on Github Actions.

**Comment by Xu-Gavin** [comment]
Fixed failing context tests by initializing a Cassandra Service on GitHub Actions. Assigning PR to @itsmarsss for review.

**Review by itsmarsss — APPROVED** [review]
Love the code, LGTM!!!!

**Pull request merged**
